[package]
name = "keymacro"
version = "0.2.0"
authors = ["Harenayo"]
edition = "2021"
description = "Keyword-like macros for Rust"
readme = "README.md"
repository = "https://github.com/harenayo/keymacro"
license = "MIT"
